spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inpatient_system?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 20
    minIdle: 10
    maxActive: 100
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB  # 设置单个文件上传的最大值
      max-request-size: 10MB  # 设置整个请求的最大值（包括表单数据和文件）
redis:
    host: 127.0.0.1
    port: 6379
    password:

file:
  upload:
    path: D://DownLoad/SpringBoot/picture/medicine/
    path.relative: /images/**


mybatis-plus:
    mapper-locations: classpath*:mapper/**/*Mapper.xml
    type-aliases-package: com.czc.domain
    configuration:
      map-underscore-to-camel-case: true
      auto-mapping-behavior: full
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #查看MP运行日志
    global-config:
      db-config:
        table-prefix: t_        #设置所有表的通用前缀名称为t_
        id-type: auto  #设置主键id字段的生成策略为参照数据库设定的策略，当前数据库设置id生成策略为自增
